import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-white`}
      >
        <header className="sticky top-0 z-50 w-full bg-white">
          <div className='navContent flex items-center justify-between px-4 py-3 container mx-auto'>
            <div className="flex items-center">
              <Link href="/" className="flex items-center text-xl font-bold space-x-2">
                <Image
                  src="/logo.svg"
                  alt="Persuade"
                  width={25}
                  height={25}
                  className="w-6 h-6"
                />
                <span>PERSUADE</span>
              </Link>
            </div>

            <nav className='navbar flex items-center justify-center space-x-4 flex-1'>
              <Link href="/dashboard" className="navLink">
                <button className="px-4 py-2 rounded-md hover:bg-gray-100">Home</button>
              </Link>
              <Link href="/about" className="navLink">
                <button className="px-4 py-2 rounded-md hover:bg-gray-100">About</button>
              </Link>
              <Link href="/pricing" className="navLink">
                <button className="px-4 py-2 rounded-md hover:bg-gray-100">Pricing</button>
              </Link>
            </nav>

            <div className="flex items-center space-x-3">
              <Link href="/signin">
                <button className="bg-white text-black hover:bg-gray-200 hover:mb-1.5 px-4 py-2 rounded-md">
                  Sign In
                </button>
              </Link>
              <Link href="/signup">
                <button className="bg-indigo-600 hover:bg-indigo-800 hover:mb-1.5 text-white px-4 py-2 rounded-md">
                  Register
                </button>
              </Link>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
