import type { Metadata } from "next";
import { Inter} from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({subsets:["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gray-100`}
      >
        <header className="sticky top-0 z-50 w-full bg-white border-b">
          <div className= 'navContent'>
            <div className='flex items-center'>
              <Link href="/" className='text-xl font-bold'>PERSUADE</Link>
              </div>
        <nav className='navbar'>
            
              <Link href="/" className="navLink">
              Home
              </Link>
              <Link href="/about" className="navLink">
              About
              </Link>
              <Link href="/pricing" className="navLink">
              Pricing
              </Link>    
          
        </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
